feat(vue): support for controlled props added to vue-searchbox
appbaseio/searchbox pull request #104
Opened 2021-05-31 15:56 UTC by anik-ghosh-au7

DRAFT PR

demo - 
https://www.loom.com/share/6fc1c1a583af492282ec1559fcbac109

2021-07-02 17:32 UTC, bietkul requested changes
@anik-ghosh-au7 Docs PR is missing

2021-07-02 17:32 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +		value: {
@anik-ghosh-au7 It should be `VueTypes.string.def('undefined')`

2021-07-02 17:32 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +			const eventNameInKebabCase = convertToKebabCase(eventName);
@anik-ghosh-au7 You don't need this utility. We can just emit the events name in kebab case only.

2021-07-02 17:32 UTC, bietkul commented on packages/vue-searchbox/src/utils/helper.js
> +export function convertToKebabCase(eventName) {
@anik-ghosh-au7 Remove it.

2021-07-13 10:23 UTC, bietkul requested changes
@anik-ghosh-au7 It seems you didn't test the changes. Check the suggestions.
How can you set the default value as `undefined` string?
Share a demo

2021-07-13 10:23 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +		value: VueTypes.string.def('undefined'),
```suggestion
		value: VueTypes.string.def(undefined),
```

2021-07-13 10:23 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +																this.withTriggerQuery('keyPress', e);
```suggestion
																this.withTriggerQuery('key-press', e);
```

2021-07-13 10:23 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +																this.withTriggerQuery('keyUp', e);
```suggestion
																this.withTriggerQuery('key-up', e);
```

2021-07-24 14:52 UTC, anik-ghosh-au7 commented
demo - https://loom.com/share/f8fc3c17952647d3859f3f08c1cb025d

2021-07-28 12:00 UTC, merged