feat(react/vue-searchbox): add suggestion type query support
appbaseio/searchbox pull request #132
Opened 2021-10-11 21:25 UTC by mohdashraf010897

**PR Type** Feature Integration

**Description** Integration of new type of query `suggestion` to fetch suggestions of different types using a single API call.

- [x]  When we're making the suggestion query (whenever autosuggest is set to `true`, use the new suggestion type instead of the current manual calls for recent/popular suggestions.
- [x]  Remove manual API calls to `popular` suggestions and `recent` suggestions
- [x]  Update the popular/recent suggestions extraction logic from the suggestion API response
- [x] You don't need to display suggestions based on the value. The API would handle it. Currently, we display suggestions based on the value. For e.g, display recent suggestions when value is empty or popular and index suggestions when value is present.
- [x] Remove all the old prop names for supporting popular and recent suggestions.
- [x] Update docs.

[🎥  Loom Demo - 12-OCT-2021-02:54-AM](https://www.loom.com/share/8bfccff9100747e8a4fcf49c609b4177)
[🎥  Loom Demo - 13-OCT-2021-04:30-PM](https://www.loom.com/share/5585d09e362841cb908c6683e27607ab)

[📄  Docs PR](https://github.com/appbaseio/Docs/pull/241) 

[📔  Notion ](https://www.notion.so/appbase/FE-Libraries-Integration-for-suggestion-type-cba01831fea4460d9639dd3df41043b0)

2021-10-12 11:06 UTC, bietkul requested changes
@mohdashraf010897 
Functionality issues
1. Ranking is managed by BE so FE don't need any logic to display popular suggestions at top or bottom. Just render the list and change icon as per the type of suggestion.
![alt de](https://i.imgur.com/e1m64Ep.png)
2. The no. of popular suggestions high because of BE issue.
![alt w](https://i.imgur.com/XSbWvpW.jpg)

2021-10-12 11:13 UTC, bietkul requested changes
Remove suggestions parsing logic from searchcomponent. The `suggestions` property is no longer needed

2021-10-12 11:13 UTC, bietkul commented on packages/vue-searchbox/src/utils/helper.js
> +	Recent: 'recent'
Add one more type as `Promoted: 'promoted'`

2021-10-12 11:13 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchComponent.jsx
> +			enableRecentSuggestions,
@mohdashraf010897 The property name in searhcbox lib is `enableRecentSearches`. We don't want to break the existing functionality. So support both names. If `enableRecentSuggestions` is not defined then fallback to `enableRecentSearches`.

2021-10-12 11:13 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchComponent.jsx
> +  		rankFeature: VueTypes.object,
You have missed some props. For e.g `enablePopularSuggestions`

2021-10-12 11:13 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchBox.jsx
> +				triggerQueryOnInit={!!context.props.autosuggest}
We only want to trigger query initially when `recentSuggestions` are enabled.

2021-10-12 13:37 UTC, mohdashraf010897 commented on packages/vue-searchbox/src/components/SearchComponent.jsx
> +  		rankFeature: VueTypes.object,
it is already there @bietkul on Line 18-19

2021-11-17 04:58 UTC, bietkul approved these changes

2021-11-17 04:58 UTC, merged