feat: introduce enableAppbase prop to enable RS-API
appbaseio/searchbox pull request #23
Opened 2020-02-20 10:07 UTC by ShahAnuj2610

how to test:

run following commands in sequence:

```
yarn && yarn dev:react
```

go to `packages/react-searchbox/examples/basic` and run
```
yarn start
```

2020-02-21 13:01 UTC, bietkul requested changes
1. No changes in `searchbox(JS)`?
2. `enableQueryRules` is missing

2020-02-21 13:01 UTC, bietkul commented on packages/react-searchbox/examples/basic/src/App.js
> +  state = { value: '' };
@ShahAnuj2610 Why did you edit the old examples, Can you please add new examples with RS API?

2020-02-21 13:01 UTC, bietkul commented on packages/searchbase/src/index.js
> +    this.nestedField = nestedField;
@ShahAnuj2610 Are you using `flow`, why do you need to change it?

2020-02-21 13:01 UTC, bietkul commented on packages/searchbase/src/index.js
> +      dataField: this.dataField,
@ShahAnuj2610 Validate `dataField`, it must be an `array`.

2020-02-21 13:01 UTC, bietkul commented on packages/searchbase/src/index.js
> +      dataField: this.dataField,
@ShahAnuj2610 Validate

2020-02-21 13:01 UTC, bietkul commented on packages/searchbase/src/index.js
> +      highlightField: this.highlightField
@ShahAnuj2610 Do we not support `customHighlight` in `searchbase`?

2020-02-21 13:11 UTC, ShahAnuj2610 commented
@bietkul for `searchbox` we just need to update `@appbaseio/searchbase` version

2020-02-21 13:12 UTC, ShahAnuj2610 commented on packages/searchbase/src/index.js
> +      highlightField: this.highlightField
no, we don't

2020-02-21 13:21 UTC, bietkul commented
@ShahAnuj2610 `settings` is also missing in the request body

2020-02-21 14:48 UTC, ShahAnuj2610 commented on packages/searchbase/src/index.js
> +    this.nestedField = nestedField;
keeping it as an empty string affects the `rs query`

2020-02-24 05:16 UTC, bietkul approved these changes

2020-02-24 05:16 UTC, merged