feat: add showDistinctSuggestions
appbaseio/searchbox pull request #26
Opened 2020-03-23 17:51 UTC by jyash97

2020-05-15 06:27 UTC, bietkul requested changes

2020-05-15 06:27 UTC, bietkul commented on packages/searchbase/src/utils.js
> +  /*
@jyash97 Update that too, this is not a proper format to write comments.

2020-08-15 15:54 UTC, bietkul commented
@jyash97 Can you resolve conflicts here

2020-08-17 13:08 UTC, jyash97 commented
Docs PR is already merged: https://github.com/appbaseio/Docs/pull/126/

2020-08-26 03:32 UTC, merged