feat: add support for queryString
appbaseio/searchbox pull request #36
Opened 2020-06-12 16:47 UTC by jyash97

## What this PR does? 

Add support for queryString

## Testing:

https://www.loom.com/share/6a41ec5adb444c04ad215c2fd7b45568
https://www.loom.com/share/5a6ed26e80fc4a958c3410d9070a40cd
https://www.loom.com/share/45a93f424bfe46d0ba6e177042f0fcad

2020-08-15 16:11 UTC, bietkul requested changes

2020-08-15 16:11 UTC, bietkul commented on packages/searchbase/src/index.js
> +    } else if (options.queryString) {
@jyash97 Set the priority to query string over search operators, check the RS code.

2020-08-15 16:11 UTC, bietkul commented
@jyash97 Where is the docs PR?

2020-08-17 13:10 UTC, jyash97 commented
> @jyash97 Where is the docs PR?


here: https://github.com/appbaseio/Docs/pull/150

2020-08-22 19:06 UTC, bietkul approved these changes

2020-08-22 19:06 UTC, merged