Update/predictive suggestions
appbaseio/searchbox pull request #64
Opened 2020-12-28 12:35 UTC by anik-ghosh-au7

Notion - https://www.notion.so/Add-predictive-suggestions-to-searchbase-searchbox-libs-b150d701887046fcb41667ef6e88ba04

Changes made -

- Added parsing logic similar to the reactive core in searchbase to the getSuggestions functions in utils
- Added support to enablePredictiveSuggestions prop in searchComponent, react-searchbox, vue-searchbox
- Added examples for enablePredictiveSuggestions in all the three packages mentioned above
- Updated the docs with the new prop

https://www.loom.com/share/3c50100e4bf94bf7aeb0a349089072e6

2021-03-05 07:00 UTC, bietkul requested changes
@anik-ghosh-au7 Make the following fixes:
1. You didn't specify the `enablePredictiveSuggestion` prop for `SearchBox` component in `React` and `Vue`.
2. Use the similar highlighting in searchbase examples that we're using in react and vue searchbox.
3. Fix conflicts

2021-03-05 07:00 UTC, bietkul commented on packages/searchbase/src/SearchComponent.d.ts
> +  enablePredictiveSuggestions: boolean;
```suggestion
  enablePredictiveSuggestions?: boolean;
```

2021-03-05 12:09 UTC, anik-ghosh-au7 commented
> @anik-ghosh-au7 Make the following fixes:
> 
> 1. You didn't specify the `enablePredictiveSuggestion` prop for `SearchBox` component in `React` and `Vue`.
> 2. Use the similar highlighting in searchbase examples that we're using in react and vue searchbox.
> 3. Fix conflicts

@bietkul made the changes

2021-03-05 14:01 UTC, bietkul approved these changes

2021-03-08 07:39 UTC, bietkul approved these changes

2021-03-08 07:41 UTC, merged