Fix(react): autosuggest prop not working correctly
appbaseio/searchbox pull request #73
Opened 2021-03-17 11:44 UTC by anik-ghosh-au7

- Issue Type - Bug

- Notion Link - https://www.notion.so/appbase/Searchbox-Fix-autosuggest-property-159e39a529004485b286845fc4ac3a22

- Description - Passing false to the autosuggest prop was still triggering the default query and showing the suggestions list.

- Fixes -
-> Don't trigger `defaultQuery` when `autosuggest` is `false`.
-> Don't fetch `recentSearches` when `autosuggest` is `false`.
-> Don't display suggestions when `autosuggest` is `false`.
-> When `autosuggest` is `false` then results should get updated on each key stroke.
-> Debounce should work as expected.

- Demo -

https://www.loom.com/share/d0524c13c37b43459f046608c2fa8e4d

2021-03-18 16:57 UTC, bietkul approved these changes

2021-03-18 17:03 UTC, bietkul commented
@anik-ghosh-au7 This PR is not well tested. Just check your video at `1:37` it is showing the suggestion box with recent searches even when the `autosuggest` is `false`.
![alt image](https://i.imgur.com/uyqtOKt.png)

As I mentioned before in the Notion card this is not the way to test debounce. If you have debounce as 500ms then the next request should get triggered after 500ms irrespective of how fast the user types input.

2021-03-18 17:04 UTC, bietkul requested changes
@anik-ghosh-au7 Check the comments

2021-03-19 05:26 UTC, anik-ghosh-au7 commented
> @anik-ghosh-au7 Check the comments

made the changes also checked the denounce function  - https://www.loom.com/share/1b7572cca06e4888a29ad9b217e6b016

2021-03-19 14:40 UTC, anik-ghosh-au7 commented
@bietkul demo - https://www.loom.com/share/781097e432ad4629baa2e91926f0eb60

2021-03-19 15:47 UTC, bietkul approved these changes

2021-03-19 15:47 UTC, bietkul commented on packages/react-searchbox/src/components/SearchBox.js
> +    if (window) {
@anik-ghosh-au7 Why are you doing it here? URLParamsProvider would automatically handle it. Please refer the vue where you said it works.

2021-03-19 15:48 UTC, merged