fix(vue): autosuggest prop not working correctly
appbaseio/searchbox pull request #74
Opened 2021-03-17 13:28 UTC by anik-ghosh-au7

- Issue Type - Bug

- Notion Link - https://www.notion.so/appbase/Searchbox-Fix-autosuggest-property-159e39a529004485b286845fc4ac3a22

- Description - Passing false to the autosuggest prop was still triggering the default query and showing the suggestions list.

Fixes -
-> Don't trigger defaultQuery when autosuggest is false.
-> Don't fetch recentSearches when autosuggest is false.
-> Don't display suggestions when autosuggest is false.
-> When autosuggest is false then results should get updated on each key stroke.
-> Debounce should work as expected.

Demo -
https://www.loom.com/share/23b335965af249d782290c5e9e9bcbd3

2021-03-18 17:12 UTC, bietkul requested changes
@anik-ghosh-au7 Check the comments on react-searchbox PR.

2021-03-19 06:40 UTC, anik-ghosh-au7 commented
> @anik-ghosh-au7 Check the comments on react-searchbox PR.

@bietkul made the changes - https://www.loom.com/share/005709fda79249f78c17c67f999d938d

2021-03-19 15:54 UTC, bietkul requested changes

2021-03-19 15:54 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchComponent.jsx
> +		autosuggest: VueTypes.bool.def(true)
@anik-ghosh-au7 Remove `autosuggest`

2021-03-19 15:54 UTC, bietkul commented on packages/vue-searchbox/src/components/SearchComponent.jsx
> +		if (triggerQueryOnInit && autosuggest) {
@anik-ghosh-au7 Remove `autosuggest`

2021-03-19 15:54 UTC, bietkul commented on packages/vue-searchbox/src/components/URLParamsProvider.jsx
> +		const { id, autosuggest } = this.$props;
Fix it

2021-03-19 17:03 UTC, bietkul approved these changes

2021-03-19 17:03 UTC, merged